// cmd/tug/starter-auth/resources/js/pages/Auth/ResetPassword.tsx
import { Form, Head, Link } from '@inertiajs/react'
import Layout from '../../Layout'
import type { PageProps } from '../../tug/pages'
import { route } from '../../tug/routes'

// ResetPassword is where the link in a reset mail leads: its token, and
// the email it went to, come in the props.
export default function ResetPassword({ token, email }: PageProps<'Auth/ResetPassword'>) {
  return (
    <Layout>
      <Head title="Choose a new password" />
      <h1>Choose a new password</h1>
      <Form action={route('password.store')} method="post" resetOnError={['password', 'password_confirmation']} className="form">
        {({ errors, processing }) => (
          <>
            <input type="hidden" name="token" value={token} />
            <label>
              Email
              <input name="email" type="email" autoComplete="username" defaultValue={email} required aria-invalid={!!errors.email} />
            </label>
            {errors.email && <p className="error">{errors.email}</p>}

            <label>
              New password
              <input name="password" type="password" autoComplete="new-password" required autoFocus aria-invalid={!!errors.password} />
            </label>
            {errors.password && <p className="error">{errors.password}</p>}

            <label>
              New password again
              <input name="password_confirmation" type="password" autoComplete="new-password" required />
            </label>
            {errors.password_confirmation && <p className="error">{errors.password_confirmation}</p>}

            <button type="submit" disabled={processing}>
              Set the password
            </button>
          </>
        )}
      </Form>
      <p className="hint">
        Has the link stopped working? <Link href={route('password.request')}>Ask for another</Link>.
      </p>
    </Layout>
  )
}

// cmd/tug/svelte-auth/resources/js/pages/Auth/ResetPassword.svelte
<script module lang="ts">
  export const layout = { title: 'Choose a new password', description: 'It logs you out everywhere you were logged in.' }
</script>

<script lang="ts">
  import { Form } from '@inertiajs/svelte'
  import LoaderCircle from '@lucide/svelte/icons/loader-circle'
  import Head from '@/Head.svelte'
  import InputError from '@/components/InputError.svelte'
  import PasswordInput from '@/components/PasswordInput.svelte'
  import TextLink from '@/components/TextLink.svelte'
  import { Button } from '@/components/ui/button'
  import { Input } from '@/components/ui/input'
  import { Label } from '@/components/ui/label'
  import type { PageProps } from '@/tug/pages'
  import { route } from '@/tug/routes'

  // ResetPassword is where the link in a reset mail leads: its token, and
  // the email it went to, come in the props.
  let { token, email }: PageProps<'Auth/ResetPassword'> = $props()
</script>

<Head title="Choose a new password" />
<Form
  action={route('password.store')}
  method="post"
  resetOnError={['password', 'password_confirmation']}
  class="flex flex-col gap-6"
>
  {#snippet children({ errors, processing })}
    <input type="hidden" name="token" value={token} />
    <div class="grid gap-2">
      <Label for="email">Email</Label>
      <Input
        id="email"
        name="email"
        type="email"
        autocomplete="username"
        value={email}
        readonly
        aria-invalid={!!errors.email}
      />
      <InputError message={errors.email} />
    </div>
    <div class="grid gap-2">
      <Label for="password">New password</Label>
      <PasswordInput id="password" name="password" autocomplete="new-password" required autofocus />
      <InputError message={errors.password} />
    </div>
    <div class="grid gap-2">
      <Label for="password_confirmation">New password again</Label>
      <PasswordInput id="password_confirmation" name="password_confirmation" autocomplete="new-password" required />
      <InputError message={errors.password_confirmation} />
    </div>
    <Button type="submit" class="w-full" disabled={processing}>
      {#if processing}
        <LoaderCircle class="animate-spin" />
      {/if}
      Set the password
    </Button>
  {/snippet}
</Form>
<p class="mt-6 text-center text-sm text-muted-foreground">
  Has the link stopped working? <TextLink href={route('password.request')}>Ask for another</TextLink>
</p>
