// cmd/tug/starter/resources/js/pages/Home.tsx
import { Form, Head } from '@inertiajs/react'
import Layout from '../Layout'
import type { PageProps } from '../tug/pages'
import { route } from '../tug/routes'

// Home is the page main.go's home handler renders. Its props, and the
// routes route() knows, are the Go ones: tug gen writes their TypeScript
// into ../tug.
export default function Home({ appName, greeting }: PageProps<'Home'>) {
  return (
    <Layout>
      <Head title="Home" />
      <h1>{appName}</h1>
      <p>{greeting}</p>

      {/* The name is checked by the server as the field is left, and again
          when the form is sent: BindValid in main.go does both. */}
      <Form action={route('hello')} method="post" className="form">
        {({ errors, processing, validate, invalid }) => (
          <>
            <label>
              What's your name?
              <input name="name" aria-invalid={invalid('name')} onBlur={() => validate('name')} />
            </label>
            {errors.name && <p className="error">{errors.name}</p>}
            <button type="submit" disabled={processing}>
              Say hello
            </button>
          </>
        )}
      </Form>

      <p className="hint">
        Change <code>main.go</code> or <code>resources/js/pages/Home.tsx</code>, and the page follows.
      </p>
    </Layout>
  )
}

// cmd/tug/vue/resources/js/pages/Home.vue
<script setup lang="ts">
import { Form, Head } from '@inertiajs/vue3'
import Layout from '../Layout.vue'
import type { Pages, SharedProps } from '../tug/pages'
import { route } from '../tug/routes'

// Home is the page main.go's home handler renders. Its props, and the
// routes route() knows, are the Go ones: tug gen writes their TypeScript
// into ../tug. Vue makes a page's props from their type, which it can't
// work out from PageProps<'Home'>, so they're spelled out.
defineProps<Pages['Home'] & SharedProps>()
</script>

<template>
  <Layout>
    <Head title="Home" />
    <h1>{{ appName }}</h1>
    <p>{{ greeting }}</p>

    <!-- The name is checked by the server as the field is left, and again
         when the form is sent: BindValid in main.go does both. -->
    <Form v-slot="{ errors, processing, validate, invalid }" :action="route('hello')" method="post" class="form">
      <label>
        What's your name?
        <input name="name" :aria-invalid="invalid('name')" @blur="validate('name')" />
      </label>
      <p v-if="errors.name" class="error">{{ errors.name }}</p>
      <button type="submit" :disabled="processing">Say hello</button>
    </Form>

    <p class="hint">
      Change <code>main.go</code> or <code>resources/js/pages/Home.vue</code>, and the page follows.
    </p>
  </Layout>
</template>
