// cmd/tug/vue-auth/resources/js/pages/Admin/FailedJobs.vue
<script setup lang="ts">
import { Head, router } from '@inertiajs/vue3'
import { RotateCcw } from '@lucide/vue'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import type { Pages, SharedProps } from '@/tug/pages'
import { route } from '@/tug/routes'

// FailedJobs is the admins' page of the jobs that failed for good, which
// are kept for a month: what each was pushed with and failed with, and a
// button that runs it again from its first attempt, as the jobs command
// does. Its handlers are in admin.go, and who may see it in abilities.go.
defineProps<Pages['Admin/FailedJobs'] & SharedProps>()

// when is a time as the page shows it, the same on the server as in any
// browser, whatever its language or zone.
function when(at: string): string {
  return `${new Date(at).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' })} UTC`
}
</script>

<template>
  <Head title="Failed jobs" />
  <div class="space-y-8">
    <div class="flex flex-wrap items-end justify-between gap-4">
      <div class="space-y-1">
        <h1 class="text-2xl font-semibold tracking-tight">Failed jobs</h1>
        <p class="text-muted-foreground">The jobs that failed for good, kept for a month, the latest first.</p>
      </div>
      <Button v-if="jobs.length > 0" variant="outline" @click="router.post(route('failed-jobs.retry-all'), {}, { preserveScroll: true })">
        <RotateCcw />
        Run them all again
      </Button>
    </div>
    <p v-if="jobs.length === 0" class="text-muted-foreground">No job has failed for good.</p>
    <ul v-else class="divide-y rounded-lg border">
      <li v-for="job in jobs" :key="job.id" class="space-y-3 p-4">
        <div class="flex items-start gap-3">
          <div class="min-w-0 flex-1 text-sm">
            <p class="flex flex-wrap items-center gap-2 font-medium">
              <span class="font-mono">{{ job.kind }}</span>
              <!-- A span, as shadcn's React Badge is: a div can't be in a p. -->
              <Badge as="span" variant="secondary">{{ job.id }}</Badge>
            </p>
            <p class="text-muted-foreground">
              Failed {{ when(job.failedAt) }}, after {{ job.attempts === 1 ? '1 attempt' : `${job.attempts} attempts` }}
            </p>
          </div>
          <Button
            variant="outline"
            size="sm"
            :aria-label="`Run job ${job.id} again`"
            @click="router.post(route('failed-jobs.retry', { id: job.id }), {}, { preserveScroll: true })"
          >
            <RotateCcw />
            Run again
          </Button>
        </div>
        <pre class="overflow-x-auto rounded bg-muted px-3 py-2 font-mono text-xs">{{ job.payload }}</pre>
        <p class="font-mono text-xs break-all text-destructive">{{ job.error }}</p>
      </li>
    </ul>
  </div>
</template>

// cmd/tug/react-auth/resources/js/pages/Admin/FailedJobs.tsx
import { Head, router } from '@inertiajs/react'
import { RotateCcw } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import type { PageProps } from '@/tug/pages'
import { route } from '@/tug/routes'

// FailedJobs is the admins' page of the jobs that failed for good, which
// are kept for a month: what each was pushed with and failed with, and a
// button that runs it again from its first attempt, as the jobs command
// does. Its handlers are in admin.go, and who may see it in abilities.go.
export default function FailedJobs({ jobs }: PageProps<'Admin/FailedJobs'>) {
  return (
    <>
      <Head title="Failed jobs" />
      <div className="space-y-8">
        <div className="flex flex-wrap items-end justify-between gap-4">
          <div className="space-y-1">
            <h1 className="text-2xl font-semibold tracking-tight">Failed jobs</h1>
            <p className="text-muted-foreground">The jobs that failed for good, kept for a month, the latest first.</p>
          </div>
          {jobs.length > 0 && (
            <Button variant="outline" onClick={() => router.post(route('failed-jobs.retry-all'), {}, { preserveScroll: true })}>
              <RotateCcw />
              Run them all again
            </Button>
          )}
        </div>
        {jobs.length === 0 ? (
          <p className="text-muted-foreground">No job has failed for good.</p>
        ) : (
          <ul className="divide-y rounded-lg border">
            {jobs.map((job) => (
              <li key={job.id} className="space-y-3 p-4">
                <div className="flex items-start gap-3">
                  <div className="min-w-0 flex-1 text-sm">
                    <p className="flex flex-wrap items-center gap-2 font-medium">
                      <span className="font-mono">{job.kind}</span>
                      <Badge variant="secondary">{job.id}</Badge>
                    </p>
                    <p className="text-muted-foreground">
                      Failed {when(job.failedAt)}, after {job.attempts === 1 ? '1 attempt' : `${job.attempts} attempts`}
                    </p>
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    aria-label={`Run job ${job.id} again`}
                    onClick={() => router.post(route('failed-jobs.retry', { id: job.id }), {}, { preserveScroll: true })}
                  >
                    <RotateCcw />
                    Run again
                  </Button>
                </div>
                <pre className="overflow-x-auto rounded bg-muted px-3 py-2 font-mono text-xs">{job.payload}</pre>
                <p className="font-mono text-xs break-all text-destructive">{job.error}</p>
              </li>
            ))}
          </ul>
        )}
      </div>
    </>
  )
}

// when is a time as the page shows it, the same on the server as in any
// browser, whatever its language or zone.
function when(at: string): string {
  return `${new Date(at).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'UTC' })} UTC`
}
