// cmd/tug/vue-auth/resources/js/pages/Auth/ConfirmPassword.vue
<script setup lang="ts">
import { Form, Head, router, usePage } from '@inertiajs/vue3'
import { KeyRound, LoaderCircle } from '@lucide/vue'
import { onMounted, ref } from 'vue'
import InputError from '@/components/InputError.vue'
import PasswordInput from '@/components/PasswordInput.vue'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { vFocus } from '@/lib/focus'
import { dismissed, getPasskey, optionsFrom, passkeysWork } from '@/lib/passkeys'
import type { Pages, SharedProps } from '@/tug/pages'
import { route } from '@/tug/routes'

// ConfirmPassword asks for the password again before the settings that
// could hand the account to someone else: passwordConfirmed in auth.go
// sends users here when they last typed it over three hours ago. One of
// their passkeys says it's them as well.
defineOptions({
  layout: {
    title: 'Confirm your password',
    description: "You're on your way to your account's settings, which ask for it once in a while.",
  },
})
defineProps<Pages['Auth/ConfirmPassword'] & SharedProps>()
const page = usePage()
const works = ref(false)
const failure = ref<string>()
onMounted(() => (works.value = passkeysWork()))

const withPasskey = async () => {
  failure.value = undefined
  try {
    const options = await optionsFrom(route('password.confirm.passkey.options'))
    if (options) router.post(route('password.confirm.passkey'), { credential: await getPasskey(options) })
  } catch (err) {
    if (!dismissed(err)) failure.value = "Your browser didn't use a passkey: try again, or type your password."
  }
}
</script>

<template>
  <Head title="Confirm your password" />
  <Form
    v-slot="{ errors, processing }"
    :action="route('password.confirm.store')"
    method="post"
    reset-on-error
    class="flex flex-col gap-6"
  >
    <div class="grid gap-2">
      <Label for="password">Password</Label>
      <PasswordInput id="password" v-focus name="password" autocomplete="current-password" required />
      <InputError :message="errors.password" />
    </div>
    <Button type="submit" class="w-full" :disabled="processing"><LoaderCircle v-if="processing" class="animate-spin" />Confirm</Button>
  </Form>
  <div v-if="passkeys && works" class="mt-4 grid gap-2">
    <Button type="button" variant="outline" class="w-full" @click="withPasskey"><KeyRound />Use a passkey</Button>
    <InputError :message="page.props.errors.passkey ?? failure" />
  </div>
</template>

// cmd/tug/react-auth/resources/js/pages/Auth/ConfirmPassword.tsx
import { Form, Head, router, usePage } from '@inertiajs/react'
import { KeyRound, LoaderCircle } from 'lucide-react'
import { useEffect, useState } from 'react'
import InputError from '@/components/input-error'
import PasswordInput from '@/components/password-input'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { dismissed, getPasskey, optionsFrom, passkeysWork } from '@/lib/passkeys'
import type { PageProps } from '@/tug/pages'
import { route } from '@/tug/routes'

// ConfirmPassword asks for the password again before the settings that
// could hand the account to someone else: passwordConfirmed in auth.go
// sends users here when they last typed it over three hours ago. One of
// their passkeys says it's them as well.
export default function ConfirmPassword({ passkeys }: PageProps<'Auth/ConfirmPassword'>) {
  const { errors } = usePage().props
  const [works, setWorks] = useState(false)
  const [failure, setFailure] = useState<string>()
  useEffect(() => setWorks(passkeysWork()), [])

  const withPasskey = async () => {
    setFailure(undefined)
    try {
      const options = await optionsFrom(route('password.confirm.passkey.options'))
      if (options) router.post(route('password.confirm.passkey'), { credential: await getPasskey(options) })
    } catch (err) {
      if (!dismissed(err)) setFailure("Your browser didn't use a passkey: try again, or type your password.")
    }
  }

  return (
    <>
      <Head title="Confirm your password" />
      <Form action={route('password.confirm.store')} method="post" resetOnError className="flex flex-col gap-6">
        {({ errors, processing }) => (
          <>
            <div className="grid gap-2">
              <Label htmlFor="password">Password</Label>
              <PasswordInput id="password" name="password" autoComplete="current-password" required autoFocus />
              <InputError message={errors.password} />
            </div>
            <Button type="submit" className="w-full" disabled={processing}>
              {processing && <LoaderCircle className="animate-spin" />}
              Confirm
            </Button>
          </>
        )}
      </Form>
      {passkeys && works && (
        <div className="mt-4 grid gap-2">
          <Button type="button" variant="outline" className="w-full" onClick={withPasskey}>
            <KeyRound />
            Use a passkey
          </Button>
          <InputError message={errors.passkey ?? failure} />
        </div>
      )}
    </>
  )
}

ConfirmPassword.layout = {
  title: 'Confirm your password',
  description: "You're on your way to your account's settings, which ask for it once in a while.",
}
